[package]
name = "cargolib"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
proc-macro2 = { version = "1.0.95", features = ["span-locations"] }
quote = "1.0"
